### ISSUE TITLE
QGIS won't close because it can't unload QNEAT3

### ISSUE THREAD

**Issue by gubuntu** [root676/QNEAT3#20]
Mac OSX
QGIS 3.4

I get this error when I try to close QGIS and when I tried to reinstall the plugin

```
Error while unloading plugin QNEAT3 

KeyError: 'QNEAT3' 
Traceback (most recent call last):
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 393, in unloadPlugin
    _unloadPluginModules(packageName)
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 421, in _unloadPluginModules
    for path in sys.modules[mod].__path__:
  File "", line 1115, in __iter__
  File "", line 1103, in _recalculate
  File "", line 1099, in _get_parent_path
KeyError: 'QNEAT3'


Python version: 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)] 
QGIS version: 3.4.11-Madeira Madeira, 9a8a6d4687 

Python Path:
/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python
/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS3.4.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages/geos
/Applications/QGIS3.4.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7
/Applications/QGIS3.4.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/lib-dynload
/Applications/QGIS3.4.app/Contents/Resources/python
/Applications/QGIS3.4.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python37.zip
/Applications/QGIS3.4.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages
/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python
.
/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/ext-libs
/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
```

**Comment by PedroVenancio** [comment]
Hi @root676 

This issue seems related to https://github.com/qgis/QGIS/issues/36488

And I also confirm it on Linux, but not on Windows.

Here is the console output when the error message show up:

```
../../src/gui/raster/qgsrendererrasterpropertieswidget.cpp:341 : (setRendererWidget) [13749ms] renderer has widgetCreateFunction
../../src/providers/grass/qgsgrass.cpp:706 : (setMapsetSearchPathWatcher) [610ms] entered.
../../src/plugins/grass/qgsgrasstools.cpp:137 : (showTabs) [0ms] mTreeModel->rowCount() = 1
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [745ms] 2020-05-29T23:05:20 Python error[1] Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 437, in unloadPlugin
    _unloadPluginModules(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 466, in _unloadPluginModules
    for path in sys.modules[mod].__path__:
  File "<frozen importlib._bootstrap_external>", line 1174, in __iter__
  File "<frozen importlib._bootstrap_external>", line 1162, in _recalculate
  File "<frozen importlib._bootstrap_external>", line 1158, in _get_parent_path
KeyError: 'QNEAT3'
../../src/providers/grass/qgsgrass.cpp:706 : (setMapsetSearchPathWatcher) [47364ms] entered.
```
I also could not find a pattern yet.
