### ISSUE TITLE
Error in running Iso-Area polygon (from layer) algorithm

### ISSUE THREAD

**Issue by Elham-f** [root676/QNEAT3#39]
I had a CSV file including start point coordinates. I read this file as a layer in QGIS. Then I saved the features of this layer (Let's consider it A) in an ESRI Shapefile format, with the CSR EPSG: 4326-WGS 84 and geometry type point. I also downloaded the road network from http://download.geofabrik.de/ and added it as a layer to QGIS. Then I saved this layer (Let's consider it B) in an ESRI Shapefile format, with the CSR EPSG: 4326-WGS 84 and geometry type LineString. Finally, in the Iso-Area as polygon (from layer) parameters tab, I selected B as the input of vector layer representing network and A as the input of start points. after running the algorithm I got this error: 
Traceback (most recent call last):

File "C:/../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QNEAT3\algs\IsoAreaAsPolygonsFromLayer.py", line 229, in processAlgorithm
net = Qneat3Network(network, input_coordinates, strategy, directionFieldName, forwardValue, backwardValue, bothValue, defaultDirection, analysisCrs, speedFieldName, defaultSpeed, tolerance, feedback)
File "C:/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QNEAT3\Qneat3Framework.py", line 130, in __init__
self.list_tiedPoints = self.director.makeGraph(self.builder, self.list_input_points, self.feedback)
Exception: unknown

The error is unknown and it is not clear what is the cause of the happening this error

**Comment by josephholler** [comment]
Try projecting all of your inputs (network layer and start points layer) to a projected coordinate system using meters as its linear units, and set the QGIS Project CRS to the same coordinate system. 
I'm not sure if this will fix your specific error, but it is necessary in order to get reasonable results from the QGIS network algorithms.

**Comment by Elham-f** [comment]
> Try projecting all of your inputs (network layer and start points layer) to a projected coordinate system using meters as its linear units, and set the QGIS Project CRS to the same coordinate system.
> I'm not sure if this will fix your specific error, but it is necessary in order to get reasonable results from the QGIS network algorithms.

Thanks for your suggestion. I did it, but unfortunately, it did not solve the problem
